version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=sessionDb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo.init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  nfc-locator:
    container_name: nfc-locator
    image: nfc-locator
    restart: unless-stopped
    env_file:
      - ./.env
    build: .
    ports:
      - "4895:4895"
    environment:
      - DB_HOST=mongo
      - DB_USER=root
      - DB_PASSWORD=nfcLocV1-gemDE
      - DB_NAME=sessionDb
      - DB_PORT=27017
    stdin_open: true
    tty: true
    links:
      - mongo
    depends_on:
      - mongo
